### ISSUE TITLE
ICAO codes

### ISSUE THREAD

**Issue by gatelli** [davidmegginson/ourairports-data#2]
When airports change their ICAO codes, I noticed "airport_ident" remains unchanged, only the "GPS CODE"(?) changed. So the runways.csv file become irrelevant as airport ident is not updated.
e.g FEG formerly UTKF is now UTFF. runway.csv still shows UTKF as reference, despite "GPS CODE" is UTFF in airports.csv
Is it possible to update airport_reference in runways.csv ? Or am I missing something ?

Thx

**Comment by davidmegginson** [comment]
Thanks for the report.  I checked the code, and it's the airport ident that gets dumped in runways.csv, so it should work as a shared key with airports.csv. Can you provide a specific example where it's not possible to link the runways to the airports?

**Comment by gatelli** [comment]
I imagine it's possible to link both csv, but it's not convenient, I was wondering why the airport ident is not the usual ident (ICAO) : it's then possible to use runways.csv only (get runways by ICAO code for example)

**Comment by davidmegginson** [comment]
The majority of the world's airports do not have an ICAO code -- that's why OurAirports has its own identifier, so that every airport can be uniquely identified. We use the ICAO code as that OA identifier when available, but the way some countries keep moving an ICAO code around from airport to airport makes it a challenge to keep it up to date.

But always, in OurAirports, use the OurAirports identifier (ident) as your primary key when joining data from the different CSV files. Do not use the GPS or IATI code, because it will often fail.

**Comment by gatelli** [comment]
Got it. Thanks for your explanation!
