### ISSUE TITLE
Include magnetic HDG

### ISSUE THREAD

**Issue by Fifcok** [davidmegginson/ourairports-data#9]
Will you add a megnetic heading of runways, now there are only true headings?

**Comment by davidmegginson** [comment]
The runway numbers give you approximate magnetic heading (except in the far north). We no longer publish magnetic variation for airports, because our data is over a decade out of date. We have it on our to-do list to find a way to reintroduce it, and if we do, you'll be able to calculate the magnetic heading by looking at the magnetic variation for each airport. but that's far in the future. 

The alternative is to get a library for magnetic variation based on latitude and longitude yourself, and then you will be able to calculate the magnetic heading for runways yourself.
